Vagrant::Config.run do |config|
    config.vm.box = "us12.04"
    config.vm.network :bridged, :bridge => "em1", :mac => "B2FA6987F603"
    config.vm.customize ["modifyvm", :id, "--memory", "512", "--name","puppet.lan"]
    config.vm.provision :shell, :path => "puppetize_1204.sh" 
end
